### PR TITLE
AEROGEAR-2850 New UPS annotations on mobile client

### PR DESCRIPTION
**Pull request by aliok**
JIRA: https://issues.jboss.org/browse/AEROGEAR-2850

Should be verified along with https://github.com/aerogear/origin-web-console/pull/50, thus wrote the verification instructions there.

How to make this branch deployed on OpenShift:

1. Just provision regular UPS APB
2. Build this branch, push it your Docker org
3. Change the deployment config for configurator on OpenShift to use your image

Summary of changes:
* Wanted to introduce some mock testing, as integration tests would be super hard.
* So, divided main.go file info multiple mockable types
* Most important business logic now lies in configOperator.go file and it is tested with an OK coverage
* The real work, annotation work, is done afterwards as I was afraid of breaking things.
* Annotations are not handled in one place, which made things easier when modifying them.

### CODE REVIEW

**Comment by aliok** [comment]
cc @pb82 mind verifying this along with the UI changes?

**Comment by darahayes** [comment]
@aliok I haven't done verification steps but from a code point of view I'm so happy with this PR. Fantastic work! 👏

**Comment by pb82** [comment]
@aliok when running `make setup` i get this error:

```
mockery -all -inpkg -dir pkg
make: mockery: No such file or directory
make: *** [setup] Error 1
```

anything else i need to do first?

**Comment by pb82** [comment]
@aliok nvm. i had to run `go get github.com/vektra/mockery/.../` first, then it worked.

**Comment by pb82** [comment]
@aliok I'm getting this errors when running the tests:

```
--- FAIL: TestConfigOperator_handleAddSecret_whenAndroid_andNoVariantExistsWithSameGoogleKey (0.00s)
panic: 
assert: mock: I don't know what to return because the method call was unexpected.
        Either do Mock.On("getPushApplicationName").Return(...) first, or remove the getPushApplicationName() call.
        This method was unexpected:
                getPushApplicationName()
                
        at: [mock_UpsClient.go:122 configOperator.go:425 configOperator.go:257 configOperator.go:94 configOperator_test.go:242] [recovered]
        panic: 
assert: mock: I don't know what to return because the method call was unexpected.
        Either do Mock.On("getPushApplicationName").Return(...) first, or remove the getPushApplicationName() call.
        This method was unexpected:
                getPushApplicationName()
                
        at: [mock_UpsClient.go:122 configOperator.go:425 configOperator.go:257 configOperator.go:94 configOperator_test.go:242]
```

I did create the mock objects before running this. Any idea?

**Comment by aliok** [comment]
@pb82 it seems I never had the tests part of CircleCI build, so when I forgot to adapt them for the latest changes, I didn't get any notification.
all green now @pb82

**Comment by aliok** [comment]
@pb82 what's the reason that checking an existing Android variant with the same Google key is removed?

Anyway, I rebased my branch, squashed commits. But I didn't want to create a single commit because of file restructuring.

Give me an +1 and I will merge.

**Pull request merged**
